version: '3.7'
services:
  nginx:
    image: 'joaolfms/monitor_sys:latest'
    volumes:
      - $PWD:/app

  node1:
    image: 'nginx'
    ports:
      - '80:80' 
    volumes:
      - $PWD:/usr/share/nginx/html:ro
