version: '3.7'
services:
  nginx:
    image: 'nginx'
    ports:
      - '80:80' 
      - '443:443'
    volumes:
      - $PWD/html:/usr/share/nginx/html:ro
      - ./nginx:/etc/nginx
      - ./cert:/cert

  nginx1:
    image: 'nginx'
    ports:
      - '81:80' 
    volumes:
      - $PWD/html1:/usr/share/nginx/html:ro
      - ./nginx:/etc/nginx
      - ./cert:/cert

  nginx2:
    image: 'nginx'
    ports:
      - '82:80' 
    volumes:
      - $PWD/html2:/usr/share/nginx/html:ro
      - ./nginx:/etc/nginx
      - ./cert:/cert
