name: CI
on:
  push:
  workflow_dispatch:
jobs:
  credentials:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: teste
        run: |
          echo ${{ github.sha }}

      - name: Configurando as credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      
      - name: Login no Docker Hub
        uses: actions-hub/docker/login@master
        env:         
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 

      - name: Buildando a imagem
        run: docker build -t joaolfms/monitor_sys:${IMAGE_TAG} --file app/Dockerfile .

      - name: Push para o Docker Hub
        uses: actions-hub/docker@master
        with:
          args: push joaolfms/monitor_sys:${{ github.sha }}

      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
            version: 3.74.1
      - name: Terraform apply
        run: |
          cd infra
          terraform init
          terraform plan
          terraform apply -auto-approve

      - name: Terraform apply
        run: |-
          cd infra
          terraform destroy -auto-approve