name: CI
on:
  push:
  workflow_dispatch:

jobs:
  credentials:
    env:
      IMAGE_TAG: ${{ github.sha }}
      ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      ACCESS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGION: ${{ secrets.AWS_REGION }}
    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@v2

      - name: Configurando as credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${AWS_ACCESS_KEY_ID}
          aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
          aws-region: ${REGION}
      
      - name: Login no Docker Hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 

      - name: Buildando a imagem
        run: docker build -t joaolfms/monitor_sys:${IMAGE_TAG} --file app/Dockerfile .

      - name: Push para o Docker Hub
        uses: actions-hub/docker@master
        with:
          args: push joaolfms/monitor_sys:${IMAGE_TAG}

      - uses: terraform/init@v1
        run: |-
          echo "Iniciando a criação do ambiente"
          terraform init

      - uses: terraform/apply@master

      - name: Terraform Apply
        run: |-
          cd infra
          terraform apply -auto-approve

      - uses: terraform/destroy@master

      - name: Terraform Destroy
        run: |-
          cd infra
          terraform destroy -auto-approve